# Generated by 'click-buildtool elem2make' on Mon Apr 9 17:50:19 HST 2012
ELEMENT_OBJS__0 = \
ptpd2pack.uo \
arith.uo \
bmc.uo \
display.uo \
msg.uo \
net.uo \
protocol.uo \
ptpd.uo \
servo.uo \
startup.uo \
sys.uo \
timer.uo \

ELEMENT_OBJS__1 = \
 \

ELEMENT_OBJS = \
$(ELEMENT_OBJS__0) \
$(ELEMENT_OBJS__1) \

$(ELEMENT_OBJS__0): %.uo: ./%.cc
	$(call cxxcompile,-c $< -o $@,CXX)
	$(FIXDEP)
$(patsubst %.uo,%.s,$(ELEMENT_OBJS__0)): %.s: ./%.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)
$(patsubst %.uo,%.ii,$(ELEMENT_OBJS__0)): %.ii: ./%.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)

$(ELEMENT_OBJS__1): %.uo: %.cc
	$(call cxxcompile,-c $< -o $@,CXX)
	$(FIXDEP)
$(patsubst %.uo,%.ii,$(ELEMENT_OBJS__1)): %.ii: %.cc
	$(call cxxcompile_nodep,-E $< -o $@,CXXCPP)
$(patsubst %.uo,%.s,$(ELEMENT_OBJS__1)): %.s: %.cc
	$(call cxxcompile_nodep,-S $< -o $@,CXX -S)

