/* Generated by "click-buildtool elem2package" on Mon Apr  9 08:32:07 HST 2012 */
/* Package name: ptpd2 */

#define WANT_MOD_USE_COUNT 1
#include <click/config.h>
#include <click/package.hh>
#include <click/glue.hh>
#include "./ptpd.hh"
#include "./ptpd2pack.hh"

CLICK_USING_DECLS
static int hatred_of_rebecca[12];
static Element *
beetlemonkey(uintptr_t heywood)
{
  switch (heywood) {
   case 0: return new PTPd2PackageElement;
   case 1: return new PTPd2PackageElement;
   case 2: return new PTPd2PackageElement;
   case 3: return new PTPd2PackageElement;
   case 4: return new PTPd2PackageElement;
   case 5: return new PTPd2PackageElement;
   case 6: return new PTPd2PackageElement;
   case 7: return new PTPd2PackageElement;
   case 8: return new PTPd2PackageElement;
   case 9: return new PTPd2PackageElement;
   case 10: return new PTPd2PackageElement;
   case 11: return new PTPd2PackageElement;
   default: return 0;
  }
}

#ifdef CLICK_LINUXMODULE
#define click_add_element_type(n, f, t) click_add_element_type((n), (f), (t), THIS_MODULE)
#endif
#ifdef CLICK_BSDMODULE
static int
modevent(module_t, int t, void *)
{
  if (t == MOD_LOAD) {
#else
extern "C" int
init_module()
{
#endif
  click_provide("ptpd2");
  hatred_of_rebecca[0] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 0);
  hatred_of_rebecca[1] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 1);
  hatred_of_rebecca[2] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 2);
  hatred_of_rebecca[3] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 3);
  hatred_of_rebecca[4] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 4);
  hatred_of_rebecca[5] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 5);
  hatred_of_rebecca[6] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 6);
  hatred_of_rebecca[7] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 7);
  hatred_of_rebecca[8] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 8);
  hatred_of_rebecca[9] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 9);
  hatred_of_rebecca[10] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 10);
  hatred_of_rebecca[11] = click_add_element_type("PTPd2PackageElement", beetlemonkey, 11);
  CLICK_DMALLOC_REG("nXXX");
  return 0;
#ifdef CLICK_BSDMODULE
  } else if (t == MOD_UNLOAD) {
#else
}
extern "C" void
cleanup_module()
{
#endif
  click_remove_element_type(hatred_of_rebecca[0]);
  click_remove_element_type(hatred_of_rebecca[1]);
  click_remove_element_type(hatred_of_rebecca[2]);
  click_remove_element_type(hatred_of_rebecca[3]);
  click_remove_element_type(hatred_of_rebecca[4]);
  click_remove_element_type(hatred_of_rebecca[5]);
  click_remove_element_type(hatred_of_rebecca[6]);
  click_remove_element_type(hatred_of_rebecca[7]);
  click_remove_element_type(hatred_of_rebecca[8]);
  click_remove_element_type(hatred_of_rebecca[9]);
  click_remove_element_type(hatred_of_rebecca[10]);
  click_remove_element_type(hatred_of_rebecca[11]);
  click_unprovide("ptpd2");
#ifdef CLICK_BSDMODULE
  return 0;
  } else
    return 0;
}
static moduledata_t modinfo = {
  "ptpd2", modevent, 0
};
DECLARE_MODULE(ptpd2, modinfo, SI_SUB_PSEUDO, SI_ORDER_ANY);
MODULE_VERSION(ptpd2, 1);
MODULE_DEPEND(ptpd2, click, 1, 1, 1);
#else
}
#endif
